type Manager {
  id: Int
  email: String
  firstname: String
  lastname: String
  restaurants: [Restaurant]
}

input CreateManager {
  email: String!
  password: String!
  firstname: String!
  lastname: String!
}

input UpdateManager {
  email: String
  password: String
  firstname: String
  lastname: String
}

type Token {
  token: String!
  expiresAt: Int
}